title: Vineel Pentrala
description: Quant Finance | MS Financial Engineering | Tech
theme: minima

# links that appear on the top‑right nav bar
header_pages:
  - profile.md
  - activities.md

github_username: vineelx

author:
  name: Vineel Pentrala
  email: vineelpentrala@gmail.com
