title: Vineel Pentrala
description: Quantitative Researcher | Financial Engineering | C++ & Python
theme: minima

# links that appear on the top‑right nav bar
header_pages:
  - profile.md
  - activities.md

github_username: vineelx

author:
  name: Vineel Pentrala
  email: vineelpentrala@gmail.com
